### ISSUE TITLE
想实现一个自定义代码块,出现一下bug

### ISSUE THREAD

**Issue by aslrz-club** [antfu/vite-plugin-md#122]
### Describe the bug

Problem encountered during the "finalize" stage of the vite-plugin-md transform pipeline:

### Reproduction

https://github.com/aslrz-club/vite-plugin-md

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 82.45 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.7.0 - /opt/homebrew/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yankeeinlondon** [comment]
Please describe the issue you are having rather than requiring someone to checkout, build, and test your code. My guess is that the latest release -- [Release v0.22.0](https://github.com/antfu/vite-plugin-md/releases/tag/v0.22.0)  -- fixes whatever problem you were having but if not then open a new issue and be sure to describe the issue _in addition to_ a minimally reproducible example.
