### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by antfu** [antfu/vite-plugin-md#3]
In the latest Vite, 

> Sourcemap is likely to be incorrect: a plugin (vite-plugin-md) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

**Comment by yankeeinlondon** [comment]
## Dep Intro

@HomyeeKing @antfu just a quick clarification ... I wanted to get this PR really ready for release and I'm a bit uncertain on an aspect I'd like feedback on. 

The ViteJS pipeline of transforms involved today to convert a Markdown file to Javascript is:
- this plugin receives imported `.md` files and tranforms them to an SFC file format (which can include custom blocks but always contains Script and Template blocks
- the `@vitejs/plugin-vue` receives this transformed file and converts it to JS and CSS

When we talk about "sourcemaps", I think @HomyeeKing's mermaid diagram is critical instruction as it points to this plugin's responsibility being the conversion of MD to SFC and leaves the second transform's responsibility (aka, SFC to JS/CSS) to `@vitejs/plugin-vue`:

```mermaid
 flowchart LR
    md[markdown]
    vueMd[vue syntax]
    compiledVue[compiled Vue]

 md  -- vite-plugin-md --> vueMd  -- vite-plugin-vue --> compiledVue
compiledVue --sourcemap2 --> vueMd --sourcemap1 --> md
```

Seems like good separation of concerns at least on the surface (though the intermediate form might be useful in understanding some issues as well) but I've run into a new complication when developing a new PR for this repo. 

## Async Transforms and Explicit Deps

This presents because this PR will make our transform work with _async_ transforms not just _sync_ transforms. This will offer superpowers in this plugin which I believe are worth having but unfortunately the way we currently plugin into the ViteJS pipeline now is too implicit.

Currently our `transform` function is defined like so:

Today our transform function looks like this:

```ts
enforce: 'pre',
transform(raw, id) {
  if (!filter(id))
    return
  try {
    return markdownToVue(config)(id, raw)
  }
  catch (e: any) {
    this.error(e)
  }
},
```

I presume we rely on the use of `{ enforce: 'pre' }` to ensure that we run our transform before `@vitejs/vitejs` comes into the picture but that stops working when we move to an _async_ version of `format`.

- Note: even though the `handleHotUpdate(ctx)` function is _already_ async it too fails understanding the dependency chain too and results in errors like this:

  ![image](https://user-images.githubusercontent.com/980757/164992803-06e2d046-faef-4b26-b18e-b657b6ba4f17.png)

> Note: looking at the modern typing of **Vite** I feel like our current function should actually be producing a type error. The intended output is a `TransformResult`

This means we return the transformed SFC code as the default/only export but this is probably too _implicit_ even though we do set `enforce: 'pre'` we have an explicit requirement that this step takes _before_ `@vite/plugin-vue` and it appears that as soon as we move to an async function here we suddenly DO NOT get the dependency chain operating in the correct order.

Now I find the _typing_ of Vite's return type for `format()` a bit confusing because it's defined twice (at least) as:

```ts
// for plugins (which is Rollup's definition)
export type TransformResult = string | null | void | Partial<SourceDescription>;
export interface SourceDescription extends Partial<PartialNull<ModuleOptions>> {
	ast?: AcornNode;
	code: string;
	map?: SourceMapInput;
}
interface ModuleOptions {
	meta: CustomPluginOptions;
	moduleSideEffects: boolean | 'no-treeshake';
	syntheticNamedExports: boolean | string;
}

// for others?
export declare interface TransformResult {
    code: string;
    map: SourceMap | null;
    etag?: string;
    deps?: string[];
    dynamicDeps?: string[];
}
```

In case, i'm coming to the conclusion that we need to solve this one of two ways:

1. we find a way to explicitly express the dependency between this repo and `@vitejs/plugin-vue`
2. we explicitly use `@vitejs/plugin-vue` inside of our transforms to remove this dependency

The first approach preserves separation of concerns while the second approach might possibly open up some useful super powers though I'm not sure we need them at the moment.

**Comment by yankeeinlondon** [comment]
My personal preference is to take approach #1 above but at the current moment I think it may be easier for me to implement #2.

**Comment by yankeeinlondon** [comment]
I am shocked to say, that apparently one of the MD files was in fact invalid so it threw off the build pipeline. As it turns out the async `transform` does work as expected but the error I received was confusing to say the least. In any event, since this appears to be ok then I will try to get the PR i'm working on to implement this feature.

**Comment by HomyeeKing** [comment]
@yankeeinlondon  you don't need to care the plugin order since the vite will handle it [internaly](https://vitejs.dev/guide/api-plugin.html#plugin-ordering), the `async` just means you can do async work in that hook, the build tool like vite\rollup will `await` your operation

so if the hooks has the tag `async`, such as [transform](https://rollupjs.org/guide/en/#transform) , just do async thing and don't care about the order

also there's thing need to be fixed that `transform` hooks needs to return `{code: xxx , map:xxx}`
https://github.com/antfu/vite-plugin-md/blob/main/src/createSfcComponent.ts#L7-L11

should be 


![image](https://user-images.githubusercontent.com/49113249/165017932-f9fdf072-da6f-4e47-81ad-f2e4a27e00d0.png)

**Comment by yankeeinlondon** [comment]
support added in `v0.17.0`
