### ISSUE TITLE
Failed to use Vue component in markdown

### ISSUE THREAD

**Issue by FuBaooo** [antfu/vite-plugin-md#90]
I think the case conversion of plug-in V14 is incorrect when converting markdown to Vue components, which leads to the problem.

When I change the plug-in version to V13, it can be loaded successfully

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/43855486/173188357-c894ab4c-2f62-4600-850e-d02fc116d4d6.png">

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/43855486/173188403-807c762c-93eb-48f9-b0c0-980845a40f6c.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/43855486/173188417-897200af-1094-4f45-a3d0-852de01b8cb7.png">

Even `ClientOnly` cannot render successfully

**↓↓↓↓↓↓↓↓↓↓↓You can see examples here↓↓↓↓↓↓↓↓↓↓↓**
[demo](https://stackblitz.com/edit/vitejs-vite-zuv4ft?file=src%2Fpages%2Fabout.md) 
**↑↑↑↑↑↑↑↑↑↑↑You can see examples here↑↑↑↑↑↑↑↑↑↑↑**

<img width="629" alt="image" src="https://user-images.githubusercontent.com/43855486/173188802-f0fa6e8f-2dbd-4d1a-a85c-52a1a62b12e6.png">

Please change the package Dependency in JSON `"vite-plugin-md": "^0.14.0"` -> `"vite-plugin-md": "0.13.1"`

**Comment by yankeeinlondon** [comment]
@FuBaooo can you produce a reproducible example on [Stackblitz](https://vite.new/vue)?

**Comment by yankeeinlondon** [comment]
it definitely does work if you use formal HTML syntax: [example](https://stackblitz.com/edit/vitejs-vite-uyxkkp?file=src/components/ToggleTheme.vue)

**Comment by yankeeinlondon** [comment]
I have been surprised for years that there hasn't been a greater push to move toward the standard. It's true there's no inherient advantage to either approach --  it's just another tabs vs spaces debate -- but the exception in this case is one is a a _standard_ and the other is not. It would appear that **Markdown It** as a parser doesn't care but **happy-dom** does and losses the capitalization in its representation of the DOM API.

**Comment by FuBaooo** [comment]
Thank you for your answer. I habitually use the way Vue is written. At the same time, I see that [antfu](https://github.com/antfu/antfu.me/blob/main/pages/talks.md) is used in this way, so I think this is correct.

I will correct the use method in my project.

> I will look a bit more into this but I believe this is because we're using DOM operations and officially uppercase characters are not valid HTML and are probably lost in one of the DOM transforms. In general I would always recommend that you use the dasherized form for component names as this is true to the specificiation.

**Comment by yankeeinlondon** [comment]
@FuBaooo components _are_ very commonly written in PascalCase and typically the first parser to receive that HTML is VueJS (or whatever framework the author is using). For this reason, so long as VueJS is happy with PascalCase it works (and VueJS definitely _is_ happy with either format). However, when it goes further down the stack ,the HTML specification for "custom components" states that non-standard components **must** be dasherized. That means not only is PascalCase incorrect but single word components are also incorrect.

I presume the reason that PascalCase is so common is that kebab-case is language incompatible with Javascript so people like the consistency in naming. That still doesn't change the fact that when it comes to the official HTML specification that this is indeed non-standard. It may be a long road before HTML custom components rule the world but by then either the HTML specification will have to have been changed or parsers like VueJS will have to have incorporated the conversion before it arrives in the browser. I'm actually interested to see what VueJS does when you turn on the "custom component" flag on it's parser. 

Anyway, because PascalCase is so common I think we need to support it ... and I think the easiest way to do so is just to convert it to kebab-case in this component. It should then work through the remainder of the transformatiion pipeline.

**Comment by FuBaooo** [comment]
> @FuBaooo components _are_ very commonly written in PascalCase and typically the first parser to receive that HTML is VueJS (or whatever framework the author is using). For this reason, so long as VueJS is happy with PascalCase it works (and VueJS definitely _is_ happy with either format). However, when it goes further down the stack ,the HTML specification for "custom components" states that non-standard components **must** be dasherized. That means not only is PascalCase incorrect but single word components are also incorrect.
> 
> I presume the reason that PascalCase is so common is that kebab-case is language incompatible with Javascript so people like the consistency in naming. That still doesn't change the fact that when it comes to the official HTML specification that this is indeed non-standard. It may be a long road before HTML custom components rule the world but by then either the HTML specification will have to have been changed or parsers like VueJS will have to have incorporated the conversion before it arrives in the browser. I'm actually interested to see what VueJS does when you turn on the "custom component" flag on it's parser.
> 
> Anyway, because PascalCase is so common I think we need to support it ... and I think the easiest way to do so is just to convert it to kebab-case in this component. It should then work through the remainder of the transformatiion pipeline.

I think it should be added

**Comment by yankeeinlondon** [comment]
this will now convert your PacalCase components to kebab-case automatically when detected in `v0.16.0`
